apiCfg:
  host: 0.0.0.0
  port: 8081
logging:
  level: debug
postgresCfg:
  - host: db
    port: 5432
    user: user
    password: pass
    database: appdb
sqliteCfg:
  path: "./db"
victoriaCfg:
  url: http://victoriametrics:8428
forecastCfg:
  url: http://forecast-service:8082
keycloakCfg:
  issuer: http://keycloak:8080/realms/myrealm
  client_id: spa-client
  client_secret: jym5bshxscBAQJqBsfo45hphL0oRdhx3
keycloakAdminCfg:
  admin_client_id: admin-service
  admin_client_secret: Bt0kQ0aQyzjbVr7Vnslr4CThTwfqVXeY
#  admin_client_secret: jym5bshxscBAQJqBsfo45hphL0oRdhx3